/**
 * CAI Design System — documentation site checks
 * The documentation (apps/docs, served at /docs/) is one page per component,
 * pattern, token family and HTML element category, generated by
 * scripts/docs-site. The routes come from the same scan as the build
 * (tests/helpers/docs-site.js): every page is checked without a list here,
 * and a test that needs an element finds its page by id (gotoId). These
 * tests compare the inventory the pages render against the package sources,
 * so the docs cannot drift from the system, and check the structure the
 * accessibility review asked for (a11y.md NAV-*, HUB-*).
 * Run with: pnpm test:ui
 */

import { test, expect } from '@playwright/test';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { gotoId, routeOf, routes, routesOf, routesWith, site } from './helpers/docs-site.js';

const fromRepo = (path) => fileURLToPath(new URL(`../${path}`, import.meta.url));

/* ---- What the packages actually contain -------------------------------- */

const tokens = JSON.parse(readFileSync(fromRepo('packages/tokens/tokens.json'), 'utf-8'));
const primitiveColors = Object.entries(tokens.color).flatMap(([family, steps]) =>
  Object.keys(steps).map((step) => `--cai-${family}-${step}`),
);

const semanticCss = readFileSync(fromRepo('packages/tokens/src/semantic.css'), 'utf-8');
const lightBlock = semanticCss.slice(
  semanticCss.indexOf('[data-theme="light"] {'),
  semanticCss.indexOf('[data-theme="dark"],'),
);
const semanticTokens = [...lightBlock.matchAll(/^\s*(--cai-[\w-]+):/gm)].map((m) => m[1]);

const componentFiles = readdirSync(fromRepo('packages/core/src/components')).filter(
  (file) => file.endsWith('.css') && file !== 'index.css',
);
const components = componentFiles.filter((file) => !file.startsWith('_'));

const objectsCss = readFileSync(fromRepo('packages/core/src/objects/_objects.css'), 'utf-8');
const layoutObjects = new Set([...objectsCss.matchAll(/^\.(o-[a-z]+)\b/gm)].map((m) => m[1]));

const utilitiesCss = readFileSync(fromRepo('packages/core/src/utilities/_utilities.css'), 'utf-8');
const utilities = new Set([...utilitiesCss.matchAll(/^\.(u-[a-z0-9-]+)\b/gm)].map((m) => m[1]));

const jsModules = readdirSync(fromRepo('packages/core/src')).filter((file) => file.endsWith('.js'));

const settingsCss = readFileSync(fromRepo('packages/core/src/settings/_settings.css'), 'utf-8');
const settingNames = (prefix) =>
  [...settingsCss.matchAll(new RegExp(`^\\s*(--cai-${prefix}-[\\w-]+):`, 'gm'))].map((m) => m[1]);

// Every CSS file of the platform package (the shell patterns and the search)
const platformDir = fromRepo('packages/platform/src/components');
const platformCss = readdirSync(platformDir)
  .filter((file) => file.endsWith('.css'))
  .map((file) => readFileSync(`${platformDir}/${file}`, 'utf-8'))
  .join('\n');
const platformClasses = [...new Set(platformCss.match(/\.cai-platform-[a-z_-]+/g))];

const MODES = ['light', 'dark', 'high-contrast'];

// One guide per core component file, each on its own page
const GUIDE_ID = { 'copy-btn': 'c-copy', 'icon-grid': 'c-icons' };
const guideIds = [...new Set(components.map((file) => GUIDE_ID[file.replace('.css', '')] ?? `c-${file.replace('.css', '')}`))];

const ALL = routes();
// A sample of layouts for the heavier checks: the hub, an index, a component, a token page, the largest page
const SAMPLE = [...new Set(['/docs/', site.byRoute.has('/docs/components/') ? '/docs/components/' : '/docs/', routeOf('c-button'), routeOf('t-semantic'), routeOf('cat-inline')])];

/* ---- Helpers ----------------------------------------------------------- */

/** Open a page and collect failed requests and console problems. */
async function open(page, path = '/docs/') {
  const requests = [];
  const failed = [];
  const problems = [];
  page.on('request', (req) => requests.push(req.url()));
  page.on('response', (res) => {
    if (res.status() >= 400) failed.push(res.url());
  });
  page.on('console', (msg) => {
    if (msg.type() === 'warning' || msg.type() === 'error') problems.push(msg.text());
  });
  page.on('pageerror', (err) => problems.push(err.message));
  await page.goto(path);
  await page.waitForLoadState('networkidle');
  await page.evaluate(() => document.fonts.ready);
  return { requests, failed, problems };
}

const theme = (page) => page.evaluate(() => document.documentElement.dataset.theme);

test.describe('Documentation site', () => {
  test.describe('every page', () => {
    for (const route of ALL) {
      test(`${route}: loads cleanly, titled and outlined, with one current page in the sidebar`, async ({ page }) => {
        const { requests, failed, problems } = await open(page, route);
        expect(failed).toEqual([]);
        expect(problems).toEqual([]);
        expect(requests.filter((url) => /themes\//.test(url))).toEqual([]);
        // cai.js would apply its own default theme: the modules are imported one by one
        expect(requests.filter((url) => /\/cai(\.min)?\.js/.test(url))).toEqual([]);
        expect(MODES).toContain(await theme(page));

        // NAV-2: one h1 (heading specimens are hidden from assistive technology), and the title starts with it
        const h1 = page.locator('h1:not([aria-hidden="true"] *)');
        await expect(h1).toHaveCount(1);
        const title = await page.title();
        expect(title.startsWith((await h1.textContent()).trim()), title).toBe(true);
        expect(title).toMatch(/CAI documentation$/);

        // NAV-3: no skipped heading level
        const levels = await page
          .locator('h1, h2, h3, h4, h5, h6')
          .evaluateAll((headings) =>
            headings
              .filter((el) => !el.closest('[aria-hidden="true"], [inert]') && (el.offsetParent !== null || el.closest('details') || el.closest('.u-sr-only')))
              .map((el) => ({ level: Number(el.tagName[1]), text: el.textContent.trim() })),
          );
        expect(levels[0].level).toBe(1);
        for (let i = 1; i < levels.length; i += 1) {
          expect(
            levels[i].level - levels[i - 1].level,
            `"${levels[i - 1].text}" (h${levels[i - 1].level}) → "${levels[i].text}" (h${levels[i].level})`,
          ).toBeLessThanOrEqual(1);
        }

        // NAV-1: landmarks; every displayed nav named, the names unique, no nav in a nav; unique ids
        await expect(page.locator('main')).toHaveCount(1);
        await expect(page.locator('body > header')).toHaveCount(1);
        await expect(page.locator('body > footer')).toHaveCount(1);
        await expect(page.locator('nav nav')).toHaveCount(0);
        const names = await page
          .locator('nav')
          .evaluateAll((navs) => navs.filter((el) => el.checkVisibility()).map((el) => el.getAttribute('aria-label') ?? document.getElementById(el.getAttribute('aria-labelledby'))?.textContent));
        expect(names.every(Boolean)).toBe(true);
        expect(new Set(names).size).toBe(names.length);
        const ids = await page.locator('[id]').evaluateAll((els) => els.map((el) => el.id));
        expect(ids.filter((id, i) => ids.indexOf(id) !== i)).toEqual([]);

        // NAV-10: exactly one aria-current="page" in the sidebar, pointing here (none on the hub area)
        const current = await page.locator('.docs-nav [aria-current="page"]').evaluateAll((links) => links.map((a) => a.getAttribute('href')));
        expect(current).toEqual(site.byRoute.get(route).meta.area === 'hub' ? [] : [route]);
        await expect(page.locator('.docs-nav .is-active')).toHaveCount(0);
        // NAV-7: nothing moves focus on load
        expect(await page.evaluate(() => document.activeElement === document.body)).toBe(true);
      });
    }
  });

  test.describe('header and color modes', () => {
    test('the header has the site links, with Docs current on the hub', async ({ page }) => {
      await open(page);

      await expect(page.locator('.site-header__nav a')).toHaveText(['Home', 'Docs', 'Components', 'GitHub']);
      await expect(page.locator('.site-header__nav a[aria-current="page"]')).toHaveText('Docs');
      // Exactly one radio group drives the tokens on this page
      await expect(page.locator('fieldset:has(input[name="cai-theme"])')).toHaveCount(1);
      await expect(page.locator('input[name="cai-theme"]')).toHaveCount(3);
      await expect(page.locator('#page-nav fieldset')).toHaveCount(0);
    });

    test('on a component page, Docs and Components are the current section', async ({ page }) => {
      await gotoId(page, 'c-button');
      await expect(page.locator('.site-header__nav a[aria-current="true"]')).toHaveText(['Docs', 'Components']);
      await expect(page.locator('.site-header__nav a[aria-current="page"]')).toHaveCount(0);
      await page.goto('/docs/components/');
      await expect(page.locator('.site-header__nav a[aria-current="page"]')).toHaveText('Components');
    });

    test('the cycle button in the footer sets the mode, under the site key', async ({ page }) => {
      await open(page);
      expect(await theme(page)).toBe('light');

      const button = page.locator('footer .cai-mode-cycle');
      await expect(button).toHaveAccessibleName('Change color mode. Current: Light');
      for (const mode of ['dark', 'high-contrast', 'light']) {
        await button.click();
        expect(await theme(page)).toBe(mode);
        await expect(page.locator('input[name="cai-theme"]:checked')).toHaveValue(mode);
      }
      await button.click();
      expect(await page.evaluate(() => localStorage.getItem('cai-site-mode'))).toBe('dark');
      // The choice follows the visitor to another page
      await page.goto(routeOf('c-button'));
      expect(await theme(page)).toBe('dark');
      await expect(button).toHaveAccessibleName('Change color mode. Current: Dark');
    });

    test('a mode can be scoped to any element', async ({ page }) => {
      await gotoId(page, 't-modes');

      const backgrounds = await page
        .locator('#t-modes .docs-scope')
        .evaluateAll((scopes) => scopes.map((el) => getComputedStyle(el).backgroundColor));
      expect(backgrounds).toHaveLength(3);
      expect(backgrounds[0]).not.toBe(backgrounds[1]);
    });
  });

  test.describe('layout', () => {
    for (const width of [1024, 1440]) {
      test(`the header sits above the sidebar and the content at ${width}px`, async ({ page }) => {
        await page.setViewportSize({ width, height: 800 });
        await open(page, routeOf('c-button'));

        const box = (selector) => page.locator(selector).evaluate((el) => el.getBoundingClientRect().toJSON());
        const [header, nav, main] = await Promise.all(['.site-header', '#page-nav', '#main-content'].map(box));
        expect(header.width).toBe(width);
        expect(nav.top).toBeGreaterThanOrEqual(header.bottom - 1);
        expect(main.top).toBeGreaterThanOrEqual(header.bottom - 1);
        expect(main.left).toBeGreaterThanOrEqual(nav.right - 1);
      });
    }

    for (const width of [320, 768]) {
      test(`the drawer toggle never covers the header at ${width}px`, async ({ page }) => {
        test.slow();
        await page.setViewportSize({ width, height: 800 });
        await open(page);

        const box = (selector) => page.locator(selector).evaluate((el) => el.getBoundingClientRect().toJSON());
        const toggle = await box('.cai-nav-toggle[popovertarget="page-nav"]');
        for (const selector of ['.site-header__brand', '.site-header__components']) {
          const b = await box(selector);
          const overlaps = !(b.right <= toggle.left || b.left >= toggle.right || b.bottom <= toggle.top || b.top >= toggle.bottom);
          expect(overlaps, selector).toBe(false);
        }
      });
    }

    for (const route of SAMPLE) {
      test(`no horizontal overflow at 320, 360, 768 and 1280px: ${route}`, async ({ page }) => {
        await open(page, route);
        for (const width of [320, 360, 768, 1280]) {
          await page.setViewportSize({ width, height: 800 });
          expect(
            await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth),
            `${width}px`,
          ).toBe(0);
        }
      });
    }
  });

  test.describe('navigation', () => {
    test('the sidebar shows the six areas and expands only the current one', async ({ page }) => {
      await gotoId(page, 'c-button');
      const areas = page.locator('.docs-nav > li > a');
      await expect(areas).toHaveText(['Get started', 'Components', 'Tokens', 'Platform', 'HTML elements', 'Accessibility']);
      await expect(page.locator('.docs-nav > li > ul')).toHaveCount(1);
      await expect(page.locator('.docs-nav a[aria-current="true"]')).toHaveText('Components');
      await expect(page.locator('.docs-nav a[aria-current="page"]')).toHaveText('Button');
      // Every component is listed, and the helpers are a named group
      const hrefs = await page.locator('.docs-nav a').evaluateAll((links) => links.map((a) => a.getAttribute('href')));
      for (const id of guideIds) expect(hrefs, id).toContain(routeOf(id));
      await expect(page.getByRole('list', { name: 'Helpers' }).getByRole('link')).toHaveText(['Layout objects', 'Utility classes', 'Keyframes']);
    });

    test('the current page is marked by more than color, in the sidebar', async ({ page }) => {
      await gotoId(page, 'c-button');
      const style = (sel) => page.locator(sel).evaluate((el) => {
        const s = getComputedStyle(el);
        return `${s.fontWeight} ${s.borderInlineStartColor}`;
      });
      expect(await style('.docs-nav a[aria-current="page"]')).not.toBe(await style('.docs-nav a[href$="/card/"]'));
    });

    test('breadcrumb and Previous / Next follow the sidebar order', async ({ page }) => {
      await gotoId(page, 'c-button');
      await expect(page.getByRole('navigation', { name: 'Breadcrumb' }).locator('a, [aria-current]')).toHaveText(['Docs', 'Components', 'Button']);
      await expect(page.locator('.docs-pager a')).toHaveText(['Previous: Breadcrumb', 'Next: Card']);
    });

    test('"On this page" is a rail with scroll spy at 1280px: aria-current="true", never "page"', async ({ page }) => {
      await page.setViewportSize({ width: 1280, height: 800 });
      await gotoId(page, 'c-button');

      const toc = page.getByRole('navigation', { name: 'On this page' });
      // Both tabs' sections, each h3 under its tab's h2 (NAV-13)
      await expect(toc.getByRole('link')).toHaveText(['Example', 'Known issues', 'Code', 'Copy the markup', 'Variants and options', 'How it works', 'Without JavaScript', 'Keyboard and ARIA', 'Design', 'When to use', 'When not to use', 'Writing the content']);
      await expect(toc.locator('li:has(> a[href="#design"]) > ul a')).toHaveText(['When to use', 'When not to use', 'Writing the content']);
      await page.locator('#how').scrollIntoViewIfNeeded();
      await expect(toc.locator('[aria-current="true"]')).toHaveCount(1);
      await expect(toc.locator('[aria-current="page"]')).toHaveCount(0);
      // the sidebar keeps its own mark
      await expect(page.locator('.docs-nav [aria-current="page"]')).toHaveText('Button');
      for (const h of await toc.getByRole('link').evaluateAll((links) => links.map((a) => a.getBoundingClientRect().height))) {
        expect(h).toBeGreaterThanOrEqual(24);
      }
    });

    test('"On this page" is closed below 1280px and opens natively', async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 800 });
      await gotoId(page, 'c-button');
      const toc = page.getByRole('navigation', { name: 'On this page' });
      await expect(toc.getByRole('link').first()).toBeHidden();
      await toc.locator('summary').click();
      await expect(toc.getByRole('link').first()).toBeVisible();
    });

    for (const width of [360, 1280]) {
      test(`every component is two links away from every page at ${width}px (ia.md §14)`, async ({ page }) => {
        // Only links visible without opening anything: the header's
        // Components, then a card of the gallery
        test.slow();
        await page.setViewportSize({ width, height: 800 });
        for (const route of [...ALL, '/']) {
          await page.goto(route);
          await expect(page.locator('.site-header__nav a[href="/docs/components/"]'), route).toBeVisible();
        }
        await page.goto('/docs/components/');
        for (const id of guideIds) {
          await expect(page.locator(`.docs-card a[href="${routeOf(id)}"]`), id).toBeVisible();
        }
      });
    }
  });

  test.describe('galleries and the A–Z index', () => {
    test('a gallery card is one link, named like its heading, with an inert thumbnail (HUB-1, HUB-2)', async ({ page }) => {
      await open(page, '/docs/components/');
      const cards = page.locator('.docs-card');
      await expect(cards).toHaveCount(20);
      for (const card of await cards.all()) {
        await expect(card.getByRole('link')).toHaveCount(1);
        await expect(card.locator('.docs-card__thumb[inert][aria-hidden="true"]')).toHaveCount(1);
      }
      // The whole card takes the click
      await page.locator('.docs-card', { hasText: 'Tooltip' }).locator('.docs-card__desc').click({ force: true });
      await expect(page).toHaveURL(new RegExp(`${routeOf('c-tooltip')}$`));
    });

    test('the A–Z index links every page, with a row of letters', async ({ page }) => {
      await open(page, '/docs/a-z/');
      const hrefs = await page.locator('.docs-az__list a').evaluateAll((links) => links.map((a) => a.getAttribute('href')));
      for (const route of ALL.filter((r) => r !== '/docs/a-z/')) expect(hrefs, route).toContain(route);
      const letters = page.getByRole('navigation', { name: 'Letters' });
      await expect(letters.locator('li')).toHaveCount(26);
      for (const href of await letters.getByRole('link').evaluateAll((links) => links.map((a) => a.getAttribute('href')))) {
        await expect(page.locator(href)).toHaveCount(1);
      }
    });
  });

  test.describe('inventory', () => {
    test('the counts in the copy match the packages', async ({ page }) => {
      const expected = {
        primitives: primitiveColors.length,
        families: Object.keys(tokens.color).length,
        semantic: semanticTokens.length,
        components: components.length,
        objects: layoutObjects.size,
        utilities: utilities.size,
        modules: jsModules.length,
      };
      const pages = routesWith('data-count=');
      expect(pages.length).toBeGreaterThan(0);
      for (const route of pages) {
        await page.goto(route);
        const counts = await page.locator('[data-count]').evaluateAll((els) =>
          els.map((el) => [el.dataset.count, Number(el.textContent)]),
        );
        for (const [key, value] of counts) expect(value, `${route} ${key}`).toBe(expected[key]);
      }
    });

    test('every primitive color has a swatch', async ({ page }) => {
      await gotoId(page, 't-primitives');

      const shown = await page
        .locator('#t-primitives .docs-swatch')
        .evaluateAll((swatches) => swatches.map((el) => el.style.getPropertyValue('--v')));
      expect(shown).toEqual(primitiveColors.map((name) => `var(${name})`));
    });

    test('every semantic token has a chip in the three modes', async ({ page }) => {
      await gotoId(page, 't-semantic');

      const chips = await page.locator('#t-semantic .docs-token').evaluateAll((all) =>
        all.map((el) => ({
          name: el.querySelector('code').textContent,
          modes: [...el.querySelectorAll('.docs-swatch')].map((swatch) => swatch.dataset.theme),
          values: [...el.querySelectorAll('.docs-swatch')].map((swatch) =>
            swatch.style.getPropertyValue('--v'),
          ),
        })),
      );
      expect(chips.map((chip) => chip.name)).toEqual(semanticTokens);
      for (const chip of chips) {
        expect(chip.modes, chip.name).toEqual(MODES);
        expect(new Set(chip.values), chip.name).toEqual(new Set([`var(${chip.name})`]));
      }
    });

    test('every scale token and setting is shown', async ({ page }) => {
      const text = async (id) => {
        await gotoId(page, id);
        return (await page.locator(`#${id}`).textContent()) ?? '';
      };
      const expectAll = (haystack, names) => {
        for (const name of names) expect(haystack, name).toContain(name);
      };

      expectAll(await text('t-spacing'), Object.keys(tokens.spacing).map((k) => `--cai-space-${k}`));
      expectAll(await text('t-sizing'), Object.keys(tokens.control).map((k) => `--cai-control-${k}`));
      expectAll(await text('t-type'), Object.keys(tokens.typography).map((k) => `--cai-${k}`));
      expectAll(await text('t-radius'), Object.keys(tokens.radius).map((k) => `--cai-radius-${k}`));
      expectAll(await text('t-shadow'), Object.keys(tokens.shadow).map((k) => `--cai-shadow-${k}`));
      expectAll(await text('c-motion'), [...settingNames('duration'), ...settingNames('easing')]);
      expectAll(await text('c-settings'), [...settingNames('z'), ...settingNames('bp')]);
    });

    test('every component has its page: example, known issues, then the Code and Design tabs (RL-18, SR-5)', async ({ page }) => {
      // ia.md §6, a11y.md TAB-16/17; the source structure is checked in tests/docs-site.test.js
      expect(guideIds.length).toBeGreaterThanOrEqual(20);
      for (const id of guideIds) {
        const route = await gotoId(page, id);
        expect(route, id).toMatch(/^\/docs\/components\/[a-z-]+\/$/);
        await expect(page.locator('h2#example'), `${id} example`).toBeVisible();
        // Known issues: visible, outside the panels, never empty
        await expect(page.locator('h2#known-issues'), `${id} known issues`).toBeVisible();
        await expect(page.locator('[role="tabpanel"] #known-issues, .cai-tabpanel #known-issues')).toHaveCount(0);
        await expect(page.locator('#known-issues + p'), id).not.toBeEmpty();
        // The same two tabs on every page, Code first and selected by default (TAB-16)
        const tablist = page.getByRole('tablist', { name: /documentation$/ });
        await expect(tablist.getByRole('tab'), id).toHaveText(['Code', 'Design']);
        await expect(tablist.getByRole('tab', { name: 'Code' })).toHaveAttribute('aria-selected', 'true');
        await expect(page.locator('#code-panel')).toBeVisible();
        await expect(page.locator('#design-panel')).toBeHidden();
        // RL-18: When to use and When not to use are on the page, in the Design tab
        for (const section of ['when', 'when-not', 'how', 'content', 'keyboard']) {
          await expect(page.locator(`#${section}`), `${id} ${section}`).toHaveCount(1);
        }
        await page.getByRole('tab', { name: 'Design' }).click();
        for (const section of ['when', 'when-not']) {
          await expect(page.locator(`#${section}`), `${id} ${section}`).toBeVisible();
          const text = await page.locator(`#${section} + p`).textContent();
          expect(text.trim().length, `${id} ${section} has content`).toBeGreaterThan(20);
        }
        await page.evaluate(() => localStorage.clear());
      }
    });

    test('every core component file is named on its page', async ({ page }) => {
      const files = [];
      for (const route of routesOf('components')) {
        await page.goto(route);
        files.push(...(await page.locator('.docs-demo__file').allTextContents()));
      }
      for (const file of componentFiles) expect(files, file).toContain(`components/${file}`);
    });

    test('every platform class is used or named on the platform pages', () => {
      const html = routesOf('platform').map((route) => site.byRoute.get(route).body).join('\n');
      for (const selector of platformClasses) expect(html, selector).toContain(selector.slice(1));
    });
  });

  test.describe('demos', () => {
    test('tabs: arrow keys, Home and End move between tabs and show their panel', async ({ page }) => {
      await gotoId(page, 'tab-summary');

      await page.focus('#tab-summary');
      await expect(page.locator('#tab-summary')).toHaveAttribute('role', 'tab');
      await page.keyboard.press('ArrowRight');
      await expect(page.locator('#tab-settings')).toBeFocused();
      await expect(page.locator('#tab-settings')).toHaveAttribute('aria-selected', 'true');
      await expect(page.locator('#panel-settings')).toBeVisible();
      await expect(page.locator('#panel-summary')).toBeHidden();

      await page.keyboard.press('End');
      await expect(page.locator('#tab-logs')).toBeFocused();
      await page.keyboard.press('Home');
      await expect(page.locator('#tab-summary')).toBeFocused();
      await page.keyboard.press('ArrowLeft');
      await expect(page.locator('#tab-logs')).toBeFocused();
    });

    test('the interactive demos are wired', async ({ page }) => {
      // Toggle drives the motion demo without extra JS
      await gotoId(page, 'c-motion');
      const dot = page.locator('#c-motion .docs-motion__dot').first();
      const before = await dot.evaluate((el) => getComputedStyle(el).insetInlineStart);
      await page.click('#c-motion .cai-toggle');
      await expect(page.locator('#c-motion .cai-toggle__input')).toBeChecked();
      await expect
        .poll(() => dot.evaluate((el) => getComputedStyle(el).insetInlineStart))
        .not.toBe(before);

      // Modal
      await gotoId(page, 'docs-modal');
      await page.click('[commandfor="docs-modal"][command="show-modal"]');
      await expect(page.locator('#docs-modal')).toBeVisible();
      await page.keyboard.press('Escape');
      await expect(page.locator('#docs-modal')).toBeHidden();

      // Players: the video knows its duration, the MIDI file was found and parsed
      await gotoId(page, 'c-player');
      await expect(page.locator('.cai-player[data-type="video"] .cai-player-duration')).not.toHaveText('0:00');
      await expect(page.locator('.cai-player[data-type="midi"] .cai-player-duration')).not.toHaveText('0:00');
      await expect(page.locator('.cai-player[data-type="midi"] .cai-player-playpause')).toBeEnabled();
    });

    test('code blocks are highlighted without an injected copy button', async ({ page }) => {
      await gotoId(page, 'c-code');

      expect(await page.locator('pre.cai-code-block .tok-name').count()).toBeGreaterThan(0);
      await expect(page.locator('.cai-code-block__copy')).toHaveCount(0);
    });

    test('the sidebar specimen is inert and says where the working one is', async ({ page }) => {
      await gotoId(page, 'c-sidebar');

      await expect(page.locator('#c-sidebar fieldset.cai-mode-switcher')).toHaveAttribute('disabled', '');
      for (const radio of await page.locator('#c-sidebar input[type="radio"]').all()) {
        await expect(radio).toBeDisabled();
      }
      await expect(page.locator('#c-sidebar .docs-demo__stage .cai-nav-toggle')).toBeDisabled();
      await expect(page.locator('#c-sidebar a[href="#page-nav"]').first()).toBeVisible();
      // No dead cycle button: the specimen is not a cycle group
      await expect(page.locator('#c-sidebar .cai-mode-cycle')).toHaveCount(0);
    });

    test('the color mode switcher has its own page: the cycle variant, its markup, init, no-JS state and names', async ({ page }) => {
      await gotoId(page, 'c-mode-switcher');

      const guide = page.locator('#c-mode-switcher');
      await expect(guide.locator('fieldset.cai-mode-switcher')).toHaveAttribute('disabled', '');
      await expect(guide.locator('a[href="#site-footer"]').first()).toBeVisible();
      await expect(guide).toContainText('cai-mode-switcher--cycle');
      await expect(guide).toContainText('initThemeCycle()');
      await expect(guide.locator('pre')).toContainText(['cai-mode-btn__icon']);
      await expect(page.locator('#keyboard ~ ul').first()).toContainText('Change color mode. Current:');
      await gotoId(page, 'h-a11y-checked');
      await expect(page.locator('#accessibility')).toContainText('three radio buttons');
    });
  });

  test.describe('long lists fold on narrow screens', () => {
    const FOLDS = routesWith('data-fold-narrow');
    const folds = (page) =>
      page.locator('details[data-fold-narrow]').evaluateAll((all) => all.map((el) => el.open));

    test('open on a wide screen', async ({ page }) => {
      await page.setViewportSize({ width: 1280, height: 800 });
      expect(FOLDS.length).toBeGreaterThan(0);
      for (const route of FOLDS) {
        await open(page, route);
        expect((await folds(page)).every(Boolean), route).toBe(true);
      }
    });

    test('closed at 360px, and opened by the native summary', async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 800 });
      for (const route of FOLDS) {
        await open(page, route);
        expect((await folds(page)).some(Boolean), route).toBe(false);
      }
      await gotoId(page, 't-semantic');
      await expect(page.locator('#t-semantic .docs-token').first()).toBeHidden();

      await page.click('#t-semantic summary');
      await expect(page.locator('#t-semantic .docs-token').first()).toBeVisible();
      await expect(page.locator('#t-semantic .docs-token')).toHaveCount(semanticTokens.length);
      expect(
        await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth),
      ).toBe(0);
    });

    test('a link to a folded card still lands on that card', async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 800 });
      await page.goto(`${routeOf('c-js')}#c-js`);
      await page.waitForLoadState('networkidle');

      expect((await folds(page)).some(Boolean)).toBe(false);
      const top = () =>
        page.evaluate(() => Math.round(document.getElementById('c-js').getBoundingClientRect().top));
      await expect.poll(top).toBeGreaterThanOrEqual(0);
      await expect.poll(top).toBeLessThan(400);
    });
  });

  test.describe('without JavaScript', () => {
    test.use({ javaScriptEnabled: false });

    for (const width of [360, 1280]) {
      test(`everything is readable at ${width}px`, async ({ page }) => {
        test.slow();
        await page.setViewportSize({ width, height: 800 });
        for (const route of ALL) {
          await page.goto(route);
          await expect(page.locator('html'), route).toHaveAttribute('data-theme', 'light');
          // Nothing is hidden but the search buttons, which only work with JavaScript
          await expect(page.locator('main [hidden]:not([data-cai-search-open])'), route).toHaveCount(0);
          expect(
            await page.locator('details[data-fold-narrow]').evaluateAll((all) => all.every((el) => el.open)),
            route,
          ).toBe(true);
          expect(
            await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth),
            route,
          ).toBe(0);
        }
        await gotoId(page, 'tab-summary');
        for (const panel of ['#panel-summary', '#panel-settings', '#panel-logs']) {
          await expect(page.locator(panel)).toBeVisible();
        }
        await gotoId(page, 'c-utilities');
        await expect(page.locator('#c-utilities tbody tr').last()).toBeVisible();
      });
    }

    test('the color mode switcher works without JavaScript', async ({ page }) => {
      await page.setViewportSize({ width: 1280, height: 800 });
      await page.goto(routeOf('c-button'));
      const background = () => page.evaluate(() => getComputedStyle(document.body).backgroundColor);
      const light = await background();
      await expect(page.locator('.cai-mode-cycle')).toBeHidden();
      await page.click('footer .cai-mode-btn:has(input[value="dark"])');
      await expect.poll(background).not.toBe(light);
    });
  });

  test.describe('copy and accessibility of the pages themselves', () => {
    test('labels say "color mode", never "theme", outside code', async ({ page }) => {
      // The custom themes are the subject of their own page, the palette is
      // for theme authors, and the accessibility statement names the shipped themes
      const THEMES_PAGE = routeOf('themes');
      const EXEMPT = [THEMES_PAGE, routeOf('t-primitives'), routeOf('h-a11y-checked')];
      for (const route of ALL.filter((r) => !EXEMPT.includes(r))) {
        await page.goto(route);
        const offenders = await page.evaluate(([themesPage, exempt]) => {
          const found = [];
          const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
          while (walker.nextNode()) {
            const node = walker.currentNode;
            if (!/theme/i.test(node.textContent)) continue;
            if (node.parentElement.closest('code, pre, script, style, #tokens-model')) continue;
            if (node.parentElement.closest(`a[href^="${themesPage}"]`)) continue;
            if (exempt.some((r) => node.parentElement.closest(`.docs-card:has(a[href="${r}"])`))) continue;
            // The name of that page, in the A–Z index
            if (/^Section of Color modes and themes$/.test(node.textContent.trim())) continue;
            // A file name: the JS module tag of a component
            if (/^JS: [\w-]+\.js$/.test(node.textContent.trim())) continue;
            found.push(node.textContent.trim());
          }
          document.querySelectorAll('[aria-label], [title], [alt]').forEach((el) => {
            for (const name of ['aria-label', 'title', 'alt']) {
              if (/theme/i.test(el.getAttribute(name) ?? '')) found.push(el.getAttribute(name));
            }
          });
          return found;
        }, [THEMES_PAGE, EXEMPT]);
        expect(offenders, route).toEqual([]);
      }
    });

    test('standalone links are targets of 24px or more', async ({ page }) => {
      for (const route of ['/docs/', '/docs/components/', routeOf('c-button'), '/docs/a-z/', '/docs/platform/']) {
        await page.goto(route);
        const heights = await page
          .locator('.docs-nav a, .docs-pager a, .docs-gallery__rows a, .docs-hub__more a, .docs-az__list a, .site-header__nav a')
          .evaluateAll((links) => links.filter((el) => el.checkVisibility()).map((el) => [el.textContent.trim(), el.getBoundingClientRect().height]));
        expect(heights.length, route).toBeGreaterThan(5);
        for (const [text, height] of heights) expect(height, `${route} ${text}`).toBeGreaterThanOrEqual(24);
      }
    });

    for (const mode of MODES) {
      test(`docs-local text has a contrast of 4.5:1 or more in ${mode}`, async ({ page }) => {
        test.slow();
        await page.addInitScript((value) => {
          localStorage.setItem('cai-site-mode', value);
        }, mode);
        let total = 0;
        for (const route of ALL) {
          await page.goto(route);
          await page.waitForLoadState('networkidle');
          expect(await theme(page)).toBe(mode);
          await page.addStyleTag({ content: '*, *::before, *::after { transition: none !important; }' });

          const { checked, failures } = await page.evaluate(() => {
            const parse = (value) => {
              const parts = value.match(/rgba?\(([^)]+)\)/)[1].split(/[,\s/]+/).filter(Boolean).map(Number);
              return { r: parts[0], g: parts[1], b: parts[2], a: parts[3] ?? 1 };
            };
            const over = (top, bottom) => ({
              r: top.r * top.a + bottom.r * (1 - top.a),
              g: top.g * top.a + bottom.g * (1 - top.a),
              b: top.b * top.a + bottom.b * (1 - top.a),
              a: 1,
            });
            const luminance = ({ r, g, b }) => {
              const channel = (v) => {
                const c = v / 255;
                return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
              };
              return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
            };
            const backgroundOf = (el) => {
              const layers = [];
              for (let node = el; node; node = node.parentElement) {
                const color = parse(getComputedStyle(node).backgroundColor);
                if (color.a > 0) layers.push(color);
                if (color.a === 1) break;
              }
              let result = layers.pop() ?? { r: 255, g: 255, b: 255, a: 1 };
              while (layers.length) result = over(layers.pop(), result);
              return result;
            };

            // Text styled by this site: an element with a docs-* class, or a
            // plain element (no class of its own) directly inside one
            const isLocal = (el) =>
              /(^|\s)docs-/.test(el.className) ||
              (!el.className && /(^|\s)docs-/.test(el.parentElement?.className ?? ''));
            const failures = [];
            let checked = 0;
            const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
            while (walker.nextNode()) {
              const node = walker.currentNode;
              const el = node.parentElement;
              if (!node.textContent.trim() || typeof el.className !== 'string' || !isLocal(el)) continue;
              if (!el.checkVisibility({ checkOpacity: true, checkVisibilityCSS: true })) continue;
              checked += 1;
              const background = backgroundOf(el);
              const color = over(parse(getComputedStyle(el).color), background);
              const [a, b] = [luminance(color), luminance(background)];
              const ratio = (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
              if (ratio < 4.5) {
                failures.push(`${ratio.toFixed(2)} ${el.tagName}.${el.className} "${node.textContent.trim().slice(0, 30)}"`);
              }
            }
            return { checked, failures: [...new Set(failures)] };
          });
          total += checked;
          expect(failures, route).toEqual([]);
        }
        expect(total).toBeGreaterThan(200);
      });
    }

    test('keyboard: skip link first, focus trapped in the modal and returned', async ({ page }) => {
      await page.setViewportSize({ width: 1280, height: 800 });
      await open(page, routeOf('docs-modal'));

      await page.keyboard.press('Tab');
      await expect(page.locator('.cai-platform-skip-link')).toBeFocused();
      await page.keyboard.press('Enter');
      await expect(page.locator('#main-content')).toBeFocused();

      const trigger = page.locator('[commandfor="docs-modal"][command="show-modal"]');
      await trigger.focus();
      await page.keyboard.press('Enter');
      await expect(page.locator('#docs-modal')).toBeVisible();
      for (let i = 0; i < 5; i += 1) {
        await page.keyboard.press('Tab');
        expect(
          await page.evaluate(
            () =>
              document.activeElement === document.body ||
              Boolean(document.activeElement.closest('#docs-modal')),
          ),
        ).toBe(true);
      }
      await page.keyboard.press('Escape');
      await expect(trigger).toBeFocused();

      await gotoId(page, 'c-table');
      const region = page.locator('#c-table .cai-table-wrap').first();
      await region.focus();
      await page.keyboard.press('Shift+Tab');
      await page.keyboard.press('Tab');
      await expect(region).toBeFocused();
      expect(await region.evaluate((el) => getComputedStyle(el).outlineStyle)).toBe('solid');
    });
  });

  test.describe('reduced motion', () => {
    test.use({ reducedMotion: 'reduce' });

    test('no smooth scrolling, and the motion demos say so', async ({ page }) => {
      await gotoId(page, 'c-motion');

      expect(
        await page.evaluate(() => getComputedStyle(document.documentElement).scrollBehavior),
      ).toBe('auto');
      await expect(page.locator('#c-motion .docs-motion__reduced')).toBeVisible();
    });
  });

  test.describe('the not-found page', () => {
    test('says the page is not here and links to the A–Z index and the docs home', async ({ page }) => {
      await page.goto('/404.html');
      await expect(page.locator('h1')).toHaveText('Page not found');
      await expect(page.locator('main').getByRole('link')).toHaveText(['A–Z index', 'Docs home']);
      // The layout has no script of its own (the dev server adds its client)
      expect(readFileSync(fromRepo('apps/docs/_layouts/not-found.html'), 'utf-8')).not.toMatch(/<script/);
    });
  });
});

test.describe('Site header and navigation toggle', () => {
  // One header on every page, from one partial of the docs site generator
  // (scripts/docs-site). The landing and the docs layouts include it. The
  // generator marks the current link.
  const read = (file) => readFileSync(fromRepo(file), 'utf-8');
  const HEADER = read('apps/docs/_partials/header.html');
  const SITE_LINKS = read('apps/docs/_partials/site-links.html');
  const INCLUDERS = {
    'apps/landing/index.html': ['header', 'site-links'],
    'apps/docs/_layouts/page.html': ['header', 'site-links'],
    'apps/docs/_layouts/not-found.html': ['header', 'site-links'],
  };

  test('every page has the same header markup, and the same site links in its drawer', () => {
    expect(HEADER).toContain('popovertarget="page-nav"');
    expect(HEADER).not.toContain('aria-current');
    // A labelled list inside the drawer's nav, not a nav in a nav (a11y.md F4)
    expect(SITE_LINKS).toContain('<ul aria-labelledby="nav-site">');
    expect(SITE_LINKS).not.toContain('<nav');
    for (const [file, partials] of Object.entries(INCLUDERS)) {
      for (const name of partials) expect(read(file), file).toContain(`<!-- cai:include ${name} -->`);
      expect(read(file), file).toMatch(/<nav class="cai-sidebar page-nav[^"]*" id="page-nav" popover aria-label="[^"]+">/);
    }
    // The drawer's site links are the header's, in the same order, less
    // Components, which stays in the header row at every width
    const hrefs = (html) => [...html.matchAll(/href="([^"]+)"/g)].map((m) => m[1]);
    const row = HEADER.match(/<nav class="site-header__nav"[\s\S]*?<\/nav>/)[0].replace(/<a class="site-header__components"[^>]*>[^<]*<\/a>/, '');
    expect(hrefs(SITE_LINKS)).toEqual(hrefs(row));
    for (const file of ['apps/landing/index.html', 'apps/docs/_layouts/page.html']) {
      expect(read(file), file).toContain('href="/apps/landing/site-header.css"');
    }
  });

  const PAGES = [
    { path: '/', current: 'Home' },
    { path: '/docs/', current: 'Docs' },
    { path: routeOf('c-button'), current: 'Docs' },
  ].filter((p, i, all) => all.findIndex((q) => q.path === p.path) === i);
  const PARTS = ['.site-header', '.site-header__menu', '.site-header__brand', '.site-header__nav'];
  const layout = (page) =>
    page.evaluate((parts) => parts.map((selector) => {
      const r = document.querySelector(selector).getBoundingClientRect();
      return [r.x, r.y, r.width, r.height].map(Math.round).join(',');
    }), PARTS);

  for (const width of [320, 360, 768, 1440]) {
    test(`the header is laid out the same on the home and docs pages at ${width}px`, async ({ page }) => {
        test.slow();
      await page.setViewportSize({ width, height: 700 });
      const boxes = [];
      for (const { path } of PAGES) {
        await page.goto(path);
        boxes.push(await layout(page));
      }
      expect(boxes[1]).toEqual(boxes[0]);
      for (const box of boxes) expect(box).toEqual(boxes[0]);
      // The menu button shows where the drawer exists, 768px and below
      await expect(page.locator('.site-header__menu')).toBeVisible({ visible: width <= 768 });
    });
  }

  for (const { path, current } of PAGES) {
    test(`one row, about 56px, with no overflow at every width: ${path}`, async ({ page }) => {
      test.slow();
      for (const width of [320, 360, 768, 1440]) {
        await page.setViewportSize({ width, height: 700 });
        await page.goto(path);
        const { height, overflow } = await page.evaluate(() => ({
          height: document.querySelector('.site-header').offsetHeight,
          overflow: document.documentElement.scrollWidth - window.innerWidth,
        }));
        expect(height, `${width}px`).toBeLessThanOrEqual(60);
        expect(overflow, `${width}px`).toBe(0);
      }
    });

    test(`the current page link is marked by more than color: ${path}`, async ({ page }) => {
      await page.goto(path);
      const link = page.locator('.site-header__nav a[aria-current]').first();
      await expect(link).toHaveText(current);
      expect(await link.evaluate((el) => getComputedStyle(el).textDecorationLine)).toBe('underline');
    });

    for (const [width, order] of [
      [360, ['.cai-platform-skip-link', '.site-header__menu', '.site-header__brand', '.site-header__components']],
      [1440, [
        '.cai-platform-skip-link',
        '.site-header__brand',
        '.site-header__nav a >> nth=0',
        '.site-header__nav a >> nth=1',
        '.site-header__nav a >> nth=2',
        '.site-header__nav a >> nth=3',
      ]],
    ]) {
      test(`the focus order follows the header row at ${width}px: ${path}`, async ({ page }) => {
        await page.setViewportSize({ width, height: 640 });
        await page.goto(path);
        for (const selector of order) {
          await page.keyboard.press('Tab');
          await expect(page.locator(selector)).toBeFocused();
        }
      });
    }

    test(`on a phone Home, Docs and GitHub are in the drawer, first; Components stays in the row: ${path}`, async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 640 });
      await page.goto(path);
      await expect(page.locator('.site-header__nav a:visible')).toHaveText(['Components']);

      await page.getByRole('button', { name: 'Menu', exact: true }).click();
      const site = page.getByRole('list', { name: 'Site' });
      await expect(site.getByRole('link')).toHaveText(['Home', 'Docs', 'GitHub']);
      await expect(site.locator('[aria-current]')).toHaveText(current);
      // first in the drawer: the first Tab from the button lands on Home
      await page.keyboard.press('Tab');
      await expect(site.getByRole('link', { name: 'Home' })).toBeFocused();
      const underline = await site.locator('[aria-current]').evaluate((el) => getComputedStyle(el).textDecorationLine);
      expect(underline).toBe('underline');
    });

    test(`on a wide screen the site links are in the header row only: ${path}`, async ({ page }) => {
      await page.setViewportSize({ width: 1440, height: 800 });
      await page.goto(path);
      await expect(page.getByRole('navigation', { name: 'Site' })).toHaveCount(1);
      await expect(page.locator('.page-nav__site')).toBeHidden();
    });

    test(`the header stays at the top while scrolling: ${path}`, async ({ page }) => {
      await page.goto(path);
      await page.evaluate(() => window.scrollTo(0, 2000));
      await expect.poll(() => page.evaluate(() => Math.round(document.querySelector('.site-header').getBoundingClientRect().top))).toBe(0);
      const height = await page.evaluate(() => document.querySelector('.site-header').offsetHeight);
      expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--site-header-h'))).toBe(`${height}px`);
    });

    test(`the hamburger turns into an X while the drawer is open, and back: ${path}`, async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 640 });
      await page.emulateMedia({ reducedMotion: 'reduce' });
      await page.goto(path);
      const bars = () => page.evaluate(() =>
        [...document.querySelectorAll('.site-header__menu-bar')].map((bar) => {
          const style = getComputedStyle(bar);
          const box = bar.getBoundingClientRect();
          return {
            transform: style.transform,
            opacity: style.opacity,
            duration: style.transitionDuration,
            middle: Math.round(box.top + box.height / 2),
          };
        }));
      const closed = await bars();
      expect(closed).toHaveLength(3);
      for (const bar of closed) {
        expect(bar.transform).toBe('none');
        expect(bar.opacity).toBe('1');
        // reduced motion: the icon swaps at once
        expect(bar.duration.split(', ').every((d) => d === '0s')).toBe(true);
      }

      const toggle = page.getByRole('button', { name: 'Menu', exact: true });
      await expect(toggle).toHaveAttribute('popovertarget', 'page-nav');
      await toggle.click();
      const drawer = page.locator('#page-nav');
      await expect(drawer).toBeVisible();
      // the drawer opens below the header: the same button closes it again
      const nav = await drawer.boundingBox();
      const btn = await toggle.boundingBox();
      expect(nav.y).toBeGreaterThanOrEqual(btn.y + btn.height);
      // An X: the outer bars cross at 45 degrees in the middle of the
      // button, the middle bar is gone. matrix(a, b, …): a = cos, b = sin.
      const open = await bars();
      const turn = (m) => m.match(/^matrix\(([^,]+), ([^,]+)/).slice(1).map(Number);
      const [a1, b1] = turn(open[0].transform);
      const [a3, b3] = turn(open[2].transform);
      expect(a1).toBeCloseTo(Math.SQRT1_2, 3);
      expect(b1).toBeCloseTo(Math.SQRT1_2, 3);
      expect(a3).toBeCloseTo(Math.SQRT1_2, 3);
      expect(b3).toBeCloseTo(-Math.SQRT1_2, 3);
      expect(open[1].opacity).toBe('0');
      const centre = Math.round(btn.y + btn.height / 2);
      expect(Math.abs(open[0].middle - centre)).toBeLessThanOrEqual(1);
      expect(Math.abs(open[2].middle - centre)).toBeLessThanOrEqual(1);
      await expect(toggle).toHaveAccessibleName('Menu');

      await toggle.click();
      await expect(drawer).toBeHidden();
      expect(await bars()).toEqual(closed);
    });

    test(`the drawer: Tab enters it, a link closes it, Escape closes it: ${path}`, async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 640 });
      await page.goto(path);
      const toggle = page.locator('.site-header__menu');
      const drawer = page.locator('#page-nav');

      await toggle.focus();
      await page.keyboard.press('Enter');
      await expect(drawer).toBeVisible();
      await page.keyboard.press('Tab');
      expect(await page.evaluate(() => document.activeElement.closest('#page-nav') !== null)).toBe(true);
      await page.keyboard.press('Escape');
      await expect(drawer).toBeHidden();
      await expect(toggle).toBeFocused();

      await toggle.click();
      // The landing's drawer lists its sections; a docs page's, the areas
      const link = drawer.locator(path === '/' ? 'a.cai-sidebar__link[href^="#"]' : '.docs-nav a').first();
      const target = await link.getAttribute('href');
      await link.click();
      await expect(page).toHaveURL(new RegExp(`${target}$`));
      await expect(drawer).toBeHidden();
    });
  }

  test('on the home page the contents are a drawer only: no sidebar on a wide screen', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 800 });
    await page.goto('/');
    await expect(page.locator('#page-nav')).toBeHidden();
    await expect(page.locator('.site-header__menu')).toBeHidden();
  });

  test('an anchored heading lands below the sticky header', async ({ page }) => {
    await gotoId(page, 'c-button');
    await page.evaluate(() => document.getElementById('how').scrollIntoView());
    const header = await page.evaluate(() => document.querySelector('.site-header').getBoundingClientRect().bottom);
    const target = await page.evaluate(() => document.getElementById('how').getBoundingClientRect().top);
    expect(target).toBeGreaterThanOrEqual(header);
  });
});
